### ISSUE TITLE
plugin error.2

### ISSUE THREAD

**Issue by yunseo2723** [Ad5001/CustomCraft#8]
Thank you for fixing the first error. But after setting the contents of the plugin I noticed another error. How should we solve it?
![15](https://user-images.githubusercontent.com/25340054/33523971-ed937672-d856-11e7-84ba-4789ee29d218.PNG)

**Comment by Ad5001** [comment]
This issue is not related to the plugin but your configuration file.
Have you set some id:meta and without puting it in quotes?
Can you send me your config file so I can see what's wrong

**Comment by yunseo2723** [comment]
[config.zip](https://github.com/Ad5001/CustomCraft/files/1524628/config.zip)
Here is config file.

**Comment by yunseo2723** [comment]
![000](https://user-images.githubusercontent.com/25340054/33524159-d582c516-d85a-11e7-94d6-1fc6960014ca.PNG)
Here is config picture.

**Comment by Ad5001** [comment]
I see your issue. When you have items with a meta (: + meta), you must put the id with quotes. For example, [351:4] would become ["351:4"]

**Comment by yunseo2723** [comment]
Thank you so much~~ I love you! you are genius
